jaffle_shop:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: jaffle-shop-505616
      dataset: jaffle_shop
      threads: 4
      timeout_seconds: 300
      location: US
