steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build-generator
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:latest
      - .
  - name: "gcr.io/cloud-builders/docker"
    id: build-operations-job
    args:
      - build
      - -f
      - operations-job.Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:latest
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:latest
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:latest

options:
  logging: CLOUD_LOGGING_ONLY
