steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -f
      - scripts/operations-job.Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:latest
      - scripts

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/operations-job:latest

options:
  logging: CLOUD_LOGGING_ONLY
