steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:latest
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/jaffle-shop-fusion/generator:latest

options:
  logging: CLOUD_LOGGING_ONLY
